### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by jmgrady**
Changes include:
 - update the `.gitignore` and `README.md` files;
 - add LICENSE file (MIT License);
 - move the installation of scripts to the end to decrease rebuilding of layers when scripts are changed;
 - move scripts to a separate sub-directory;
 - fix permissions on `ecr-get-login.sh`.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/aws-kubectl/1)

### CODE REVIEW

**Comment by johnthagen** [comment]
___
*[.gitignore, line 13 at r1](https://reviewable.io/reviews/sillsdev/aws-kubectl/1#-Mh-7G-XCsE7zz-n5eS1:-Mh-7G-XCsE7zz-n5eS2:b-s4inyp) ([raw file](https://github.com/sillsdev/aws-kubectl/blob/ac16eee1d58c557c606fedd974cbd2428c188521/.gitignore#L13)):*
> ```ignore
> \#*#
> 
> # JetBrains Rider
> ```

Maybe change this to "JetBrains IntelliJ-based". It's likely someone would actually use PyCharm or IntelliJ to open this repo rather than Rider.

**Comment by johnthagen** [comment]
___
*[Dockerfile, line 27 at r1](https://reviewable.io/reviews/sillsdev/aws-kubectl/1#-Mh-7kFgCbkM-CgA5O6W:-Mh-7kFgCbkM-CgA5O6X:bxwl4tz) ([raw file](https://github.com/sillsdev/aws-kubectl/blob/ac16eee1d58c557c606fedd974cbd2428c188521/Dockerfile#L27)):*
> ```Dockerfile
> USER user
> WORKDIR /home/user
> ENV PATH /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/user/.local/bin
> ```

Is it possible to prepend to the existing `$PATH` if that is the intent rather than duplicating the entire contents?

**Comment by johnthagen** [comment]
___
*[Dockerfile, line 1 at r1](https://reviewable.io/reviews/sillsdev/aws-kubectl/1#-Mh-7xuv0CeVJnkU2p9c:-Mh-7xuv0CeVJnkU2p9d:bs22jd3) ([raw file](https://github.com/sillsdev/aws-kubectl/blob/8201e6170cb9f303d5c37451923d44bbec33ce07/Dockerfile#L1)):*
> ```Dockerfile
> FROM ubuntu:focal
> ```

I personally find it easier to read `ubuntu:20.04` as I find it's hard to keep up with the codenames and remember which year they were released.

**Comment by johnthagen** [comment]
___
*[Dockerfile, line 4 at r1](https://reviewable.io/reviews/sillsdev/aws-kubectl/1#-Mh-8Ifu5WDL3J8upybg:-Mh-8Ifu5WDL3J8upybh:bh7xuba) ([raw file](https://github.com/sillsdev/aws-kubectl/blob/ac16eee1d58c557c606fedd974cbd2428c188521/Dockerfile#L4)):*
> ```Dockerfile
> LABEL maintainer="Jim Grady <jimgrady.jg@gmail.com>"
> 
> # Install AWS-CLI version 2
> ```

Could we add a URL reference to the docs where you pulled these commands from? That way, if they ever change someone has a quick way to look them up.

**Comment by johnthagen** [comment]
___
*[Dockerfile, line 2 at r1](https://reviewable.io/reviews/sillsdev/aws-kubectl/1#-Mh-ABtY9jDDLYAZ666g:-Mh-ABtY9jDDLYAZ666h:b-5xtn8n) ([raw file](https://github.com/sillsdev/aws-kubectl/blob/8201e6170cb9f303d5c37451923d44bbec33ce07/Dockerfile#L2)):*
> ```Dockerfile
> FROM ubuntu:focal
> LABEL maintainer="Jim Grady <jimgrady.jg@gmail.com>"
> ```

It would be helpful to add a GitHub Actions CI job that verified that the Dockerfile builds successfully (helpful to spot errors in future PRs).

This is very simple to do with GitHub Actions and an example is here: https://github.com/sillsdev/TheCombine/blob/e376a137f06d4e970fecb99e635cb2e2a64f7416/.github/workflows/frontend.yml#L38

**Comment by johnthagen** [comment]
___
*[README.md, line 1 at r1](https://reviewable.io/reviews/sillsdev/aws-kubectl/1#-Mh-Bkpr4hZuykVJ5jF9:-Mh-Bkpr4hZuykVJ5jFA:b-mkwiaa) ([raw file](https://github.com/sillsdev/aws-kubectl/blob/ac16eee1d58c557c606fedd974cbd2428c188521/README.md#L1)):*
> ```Markdown
> The Docker image is based off of `ubuntu:focal` and adds:
> ```

I think it would be helpful to add a link to where this is stored in Docker Hub: https://hub.docker.com/r/sillsdev/aws-kubectl

Also perhaps provide a short example on how someone is expected to use this in a derived image?

```
FROM sillsdev/aws-kubectl
# Set ENV variables
# etc.
```

**Comment by johnthagen** [comment]
___
*[README.md, line 3 at r1](https://reviewable.io/reviews/sillsdev/aws-kubectl/1#-Mh-CPm49Jj2AXhJAs3j:-Mh-CPm49Jj2AXhJAs3k:b-40cmbs) ([raw file](https://github.com/sillsdev/aws-kubectl/blob/ac16eee1d58c557c606fedd974cbd2428c188521/README.md#L3)):*
> ```Markdown
> The Docker image is based off of `ubuntu:focal` and adds:
> 
> - aws-cli version 2;
> ```

The default `docker pull` command that is shown on Docker Hub doesn't work yet because there isn't a `latest` tag. Do you think we should add that to make experimenting with this image easier for prospective users?



```
 docker pull sillsdev/aws-kubectl
Using default tag: latest
Error response from daemon: manifest for sillsdev/aws-kubectl:latest not found: manifest unknown: manifest unknown
```

**Review by johnthagen — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/aws-kubectl/1)* status: all files reviewed, 7 unresolved discussions (waiting on @jmgrady)

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/aws-kubectl/1)* status: all files reviewed, 5 unresolved discussions (waiting on @johnthagen)

___
*[.gitignore, line 13 at r1](https://reviewable.io/reviews/sillsdev/aws-kubectl/1#-Mh-7G-XCsE7zz-n5eS1:-Mh-dS3K3GCKTFrT4JEM:b-896fix) ([raw file](https://github.com/sillsdev/aws-kubectl/blob/ac16eee1d58c557c606fedd974cbd2428c188521/.gitignore#L13)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Maybe change this to "JetBrains IntelliJ-based". It's likely someone would actually use PyCharm or IntelliJ to open this repo rather than Rider.
</blockquote></details>

Done.
___
*[Dockerfile, line 1 at r1](https://reviewable.io/reviews/sillsdev/aws-kubectl/1#-Mh-7xuv0CeVJnkU2p9c:-Mh-N9oi7d7r9joVgqRt:b-896fix) ([raw file](https://github.com/sillsdev/aws-kubectl/blob/8201e6170cb9f303d5c37451923d44bbec33ce07/Dockerfile#L1)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I personally find it easier to read `ubuntu:20.04` as I find it's hard to keep up with the codenames and remember which year they were released.
</blockquote></details>

Done.
___
*[Dockerfile, line 2 at r1](https://reviewable.io/reviews/sillsdev/aws-kubectl/1#-Mh-ABtY9jDDLYAZ666g:-Mh-O3cgBeIZ6oNIcZdj:b-896fix) ([raw file](https://github.com/sillsdev/aws-kubectl/blob/8201e6170cb9f303d5c37451923d44bbec33ce07/Dockerfile#L2)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

It would be helpful to add a GitHub Actions CI job that verified that the Dockerfile builds successfully (helpful to spot errors in future PRs).

This is very simple to do with GitHub Actions and an example is here: https://github.com/sillsdev/TheCombine/blob/e376a137f06d4e970fecb99e635cb2e2a64f7416/.github/workflows/frontend.yml#L38
</blockquote></details>

Done.
___
*[Dockerfile, line 4 at r1](https://reviewable.io/reviews/sillsdev/aws-kubectl/1#-Mh-8Ifu5WDL3J8upybg:-Mh-P51i0G3X97Nhq8vj:bkc9tih) ([raw file](https://github.com/sillsdev/aws-kubectl/blob/ac16eee1d58c557c606fedd974cbd2428c188521/Dockerfile#L4)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Could we add a URL reference to the docs where you pulled these commands from? That way, if they ever change someone has a quick way to look them up.
</blockquote></details>

Done.  Also used a more recent URL.
___
*[Dockerfile, line 27 at r1](https://reviewable.io/reviews/sillsdev/aws-kubectl/1#-Mh-7kFgCbkM-CgA5O6W:-Mh-PHn5-P6gh4Rq-WWN:b-qgsclt) ([raw file](https://github.com/sillsdev/aws-kubectl/blob/ac16eee1d58c557c606fedd974cbd2428c188521/Dockerfile#L27)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

Is it possible to prepend to the existing `$PATH` if that is the intent rather than duplicating the entire contents?
</blockquote></details>

I have removed this.  This was based off of an earlier design and is no longer necessary.
___
*[README.md, line 1 at r1](https://reviewable.io/reviews/sillsdev/aws-kubectl/1#-Mh-Bkpr4hZuykVJ5jF9:-Mh-Rc080qoV6lRRh4W0:b-896fix) ([raw file](https://github.com/sillsdev/aws-kubectl/blob/ac16eee1d58c557c606fedd974cbd2428c188521/README.md#L1)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I think it would be helpful to add a link to where this is stored in Docker Hub: https://hub.docker.com/r/sillsdev/aws-kubectl

Also perhaps provide a short example on how someone is expected to use this in a derived image?

```
FROM sillsdev/aws-kubectl
# Set ENV variables
# etc.
```
</blockquote></details>

Done.
___
*[README.md, line 3 at r1](https://reviewable.io/reviews/sillsdev/aws-kubectl/1#-Mh-CPm49Jj2AXhJAs3j:-Mh-RtCQCGK3MvO9Y1oj:bs7wumx) ([raw file](https://github.com/sillsdev/aws-kubectl/blob/ac16eee1d58c557c606fedd974cbd2428c188521/README.md#L3)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

The default `docker pull` command that is shown on Docker Hub doesn't work yet because there isn't a `latest` tag. Do you think we should add that to make experimenting with this image easier for prospective users?



```
 docker pull sillsdev/aws-kubectl
Using default tag: latest
Error response from daemon: manifest for sillsdev/aws-kubectl:latest not found: manifest unknown: manifest unknown
```
</blockquote></details>

Done.

**Comment by johnthagen** [comment]
___
*[README.md, line 1 at r1](https://reviewable.io/reviews/sillsdev/aws-kubectl/1#-Mh-Bkpr4hZuykVJ5jF9:-Mh-mvw168SBLBhOsEkc:b-nb9hkf) ([raw file](https://github.com/sillsdev/aws-kubectl/blob/ac16eee1d58c557c606fedd974cbd2428c188521/README.md#L1)):*
<details><summary><i>Previously, jmgrady (Jim Grady) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I was thinking to put this information into the README so that if someone browses the GitHub repo they can see immediately a link to where the image is hosted on Docker Hub.

What do you think?

**Review by johnthagen — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/aws-kubectl/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

**Review by jmgrady — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/aws-kubectl/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmgrady)

___
*[README.md, line 1 at r1](https://reviewable.io/reviews/sillsdev/aws-kubectl/1#-Mh-Bkpr4hZuykVJ5jF9:-Mh-nJKQ22z3seydTWoG:b-cghznk) ([raw file](https://github.com/sillsdev/aws-kubectl/blob/ac16eee1d58c557c606fedd974cbd2428c188521/README.md#L1)):*
<details><summary><i>Previously, johnthagen wrote…</i></summary><blockquote>

I was thinking to put this information into the README so that if someone browses the GitHub repo they can see immediately a link to where the image is hosted on Docker Hub.

What do you think?
</blockquote></details>

Actually, it is in the README.md.  What I did to resolve it was to add a pointer to the README.md.

**Pull request merged**
